apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: three-tier # Deploy Node Exporter in the same namespace
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter # Ensures all pods use the same label
  template:
    metadata:
      labels:
        app: node-exporter # Label for Node Exporter pods
    spec:
      containers:
      - name: node-exporter
        image: prom/node-exporter # Node Exporter official image
        ports:
        - containerPort: 9100 # Node Exporter default port
        livenessProbe:
          httpGet:
            path: /metrics # Node Exporter exposes metrics on this path
            port: 9100
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics # Readiness probe for Node Exporter
            port: 9100
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
  namespace: three-tier
  labels:
    app: node-exporter
spec:
  type: ClusterIP # Internal service
  ports:
  - port: 9100 # Node Exporter service port
    targetPort: 9100
  selector:
    app: node-exporter
